/* Run: node tests/regression.cjs. No third-party dependencies required. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const {Worker}=require('node:worker_threads');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const source=html.split('<script>')[1].split('</script>')[0].split('/* ======================= AVVIO')[0];
const run=new Function(source+';return code=>eval(code);')();
const initial=run('JSON.stringify(state)');
function reset(){run(`state=JSON.parse(${JSON.stringify(initial)});state.anno=2026;state.mese=9;state.codiceVariante='regression';state.persone=['ANNA','BRUNO','CARLO','DARIO','ELENA','FRANCO','GINA','HUGO'];`);}
function test(name,fn){reset();fn();console.log('OK',name);}
function ctx(){return run(`({anno:state.anno,mese:state.mese,persone:state.persone,regole:state.regole,regoleCustom:state.regoleCustom,personaIndisponibile:personaIndisponibileGlobale,fissi:state.fissi,continuita:continuitaMesePrecedente()})`);}
const validate=()=>run('validaPianoIndipendente')(run('state.griglia'),ctx());
const grid=()=>run(`state.griglia=Object.fromEntries(Array.from({length:30},(_,i)=>[i+1,{CUCINA:'ANNA',SERVIZIO:'BRUNO'}]));state.regole.riposoMinimo=false;state.regole.noStessoWeekend=false;`);
(async()=>{
test('version metadata consistent and comparison correct',()=>{const info=JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8'));assert.equal(run('APP_VERSION'),info.version);assert(run(`confrontaVersioni('2.3.0','2.2.9')`)>0);assert.equal(run(`confrontaVersioni('2.2','2.2.0')`),0);assert(run(`confrontaVersioni('2.1.9','2.2.0')`)<0);assert(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes(`const VERSIONE = "${info.cache}"`));});
test('baseline valid and deterministic',()=>{const a=run('generaGriglia()'),b=run('generaGriglia()');assert.equal(a.ok,true);assert.equal(a.pianoInfo.validato,true);assert.deepEqual(a.griglia,b.griglia);});
test('future training never enables earlier shifts',()=>{run(`state.profili.ANNA={affCucinaRichiesti:1};state.affiancamenti=[{giorno:30,ruolo:'CUCINA',nome:'ANNA'}];`);const r=run('generaGriglia()');assert.equal(r.ok,true);assert(!Object.entries(r.griglia).some(([g,d])=>g<30&&d.CUCINA==='ANNA'));});
test('earlier training enables following days',()=>{run(`state.profili.ANNA={affCucinaRichiesti:1};state.affiancamenti=[{giorno:10,ruolo:'CUCINA',nome:'ANNA'}];`);assert.equal(run(`affiancamentiCompletati('ANNA','CUCINA',10)`),0);assert.equal(run(`affiancamentiCompletati('ANNA','CUCINA',11)`),1);const r=run('generaGriglia()');assert.equal(r.ok,true);assert(!Object.entries(r.griglia).some(([g,d])=>g<=10&&d.CUCINA==='ANNA'));});
test('future archived months do not count as completed',()=>{run(`state.storico['2026-10']={persone:state.persone,griglia:{1:{affCucina:'ANNA'}}}`);assert.equal(run(`affiancamentiCompletati('ANNA','CUCINA',1)`),0);});
test('manual changes update historical continuity on save',()=>{global.localStorage={setItem(){}};run(`state.griglia={30:{CUCINA:'ANNA',SERVIZIO:'BRUNO'}};state.pianoFingerprint=fingerprintDi(datiRilevantiPiano());salvaNelloStorico();state.griglia[30].CUCINA='CARLO';ricalcolaStatsDaGriglia();rivalidaDopoModificaManuale();salvaLocale();state.mese=10`);const c=run('continuitaMesePrecedente()');assert(!c.ANNA);assert.equal(c.CARLO.giornoVirtuale,0);});
test('missing shifts flagged',()=>{run('state.griglia={}');assert.equal(validate().filter(v=>v.testo.startsWith('Turno scoperto:')).length,60);});
test('supporter unavailability and double support flagged',()=>{grid();run(`state.griglia[1].affCucina='CARLO';state.griglia[1].affServizio='CARLO';state.indisponibilita=[{persona:'CARLO',tipo:'SPECIFICA',params:{giorno:1}}]`);const v=validate();assert(v.some(v=>v.testo.startsWith('Doppio affiancamento')));assert(v.some(v=>v.testo.includes('Indisponibilità violata: CARLO')));});
test('manual team and support participate in rest constraints',()=>{grid();run(`state.regole.riposoMinimo=true;state.griglia[2].CUCINA='CARLO';state.griglia[1].affCucina='CARLO';state.giorniSpeciali=[{giorno:3,etichetta:'Festa',cucina:['CARLO'],servizio:['DARIO']}]`);assert(validate().filter(v=>v.testo.includes('Riposo minimo violato: CARLO')).length>=2);});
test('fixed overrides remain supported and explicit',()=>{run(`state.fissi=[{giorno:1,ruolo:'CUCINA',nome:'ANNA'},{giorno:2,ruolo:'CUCINA',nome:'ANNA'}]`);const r=run('generaGriglia()');assert.equal(r.ok,true);assert.equal(r.griglia[1].CUCINA,'ANNA');assert(r.conflitti.some(v=>v.includes('Deroga per turno fisso')));});
test('fixed shift cannot hide titular/support overlap',()=>{run(`state.fissi=[{giorno:1,ruolo:'CUCINA',nome:'ANNA'}];state.affiancamenti=[{giorno:1,ruolo:'SERVIZIO',nome:'ANNA'}]`);assert.equal(run('generaGriglia().ok'),false);});
test('malformed backups rejected without mutation',()=>{const before=run('JSON.stringify(state)');assert(run('validaStrutturaBackup({...state,persone:[null],fissi:[null]})'));assert(run('validaStrutturaBackup({...state,regoleCustom:[{tipo:"NON_CON",params:null}]})'));assert.equal(run('JSON.stringify(state)'),before);assert.equal(run('validaStrutturaBackup(state)'),null);});
test('storage failures surfaced',()=>{global.localStorage={setItem(){throw new Error('quota')}};assert.equal(run('salvaLocale()'),false);assert(run('ultimoErroreSalvataggio').includes('non riuscito'));});
test('weekends counted distinctly when double shifts allowed',()=>{grid();run(`state.griglia[5]={CUCINA:'CARLO',SERVIZIO:'CARLO'};state.griglia[6]={CUCINA:'CARLO',SERVIZIO:'CARLO'};ricalcolaStatsDaGriglia()`);assert.equal(run('state.stats.he.CARLO'),1);});
test('weekly continuity includes previous month work',()=>{run(`state.storico['2026-8']={persone:state.persone,griglia:{31:{CUCINA:'CARLO',SERVIZIO:'DARIO'}}}`);assert.equal(run('continuitaMesePrecedente().CARLO.turniSettimana'),1);});
test('no candidates yields precise diagnostic',()=>{run(`state.persone.forEach(p=>state.profili[p]={cucina:false})`);const r=run('generaGriglia()');assert.equal(r.ok,false);assert(r.conflitti.some(v=>v.includes('CUCINA, giorno 1')));});
test('legacy current plan migrated without losing assignments',()=>{grid();run(`state.pianoFingerprint=(()=>{const input=JSON.parse(datiRilevantiPiano());delete input.storicoRilevante;return fingerprintDi(JSON.stringify(input));})();`);const g=run('JSON.stringify(state.griglia)');run('migraVersione2()');assert.equal(run('JSON.stringify(state.griglia)'),g);assert.equal(run('pianoAggiornato()'),true);assert.equal(run('state.versioneDati'),2);});
test('archive snapshots round-trip and reject corrupted inputs',()=>{grid();run(`state.pianoFingerprint=fingerprintDi(datiRilevantiPiano());ricalcolaStatsDaGriglia();salvaNelloStorico()`);assert.equal(run('validaStrutturaBackup(state)'),null);run(`state.storico['2026-9'].input.mese=10`);assert(run('validaStrutturaBackup(state)'));});
test('archived snapshot restores original month and validates',()=>{grid();run(`state.pianoFingerprint=fingerprintDi(datiRilevantiPiano());salvaNelloStorico();state.mese=10;state.griglia=null;refreshUI=()=>{};aggiornaUndo=()=>{};`);global.document={getElementById:id=>id==='archivioMese'?{value:'2026-9'}:{textContent:'',style:{}}};global.localStorage={setItem(){}};run('ripristinaMese()');assert.equal(run('state.mese'),9);assert.equal(run('state.griglia[1].CUCINA'),'ANNA');assert.equal(run('pianoAggiornato()'),true);assert.equal(run('validaStrutturaBackup(state)'),null);delete global.document;});
test('cancelling a variant preserves the previous plan and code',()=>{grid();run(`state.pianoFingerprint=fingerprintDi(datiRilevantiPiano())`);const before=run('JSON.stringify(state)');const elements={};global.document={getElementById:id=>elements[id]||=( {style:{},textContent:'',value:0,disabled:false,hidden:true} )};global.Worker=class{postMessage(){}terminate(){this.terminated=true;}};run(`eseguiGenerazione('different-code');annullaGenerazione()`);assert.equal(run('JSON.stringify(state)'),before);assert.equal(elements.btnGenera.disabled,false);assert.equal(elements.btnAnnullaGenerazione.hidden,true);delete global.document;delete global.Worker;});
reset();const swListeners={},deleted=[];const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');const scope='https://example.test/turni/';
let pending;vm.runInNewContext(sw,{self:{registration:{scope},addEventListener:(k,fn)=>swListeners[k]=fn,clients:{claim:()=>Promise.resolve()}},caches:{keys:()=>Promise.resolve(['other-app','generatore-turni:'+scope+':old','generatore-turni:https://example.test/other/:old']),delete:k=>{deleted.push(k);return Promise.resolve(true);}},URL});swListeners.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(deleted,['generatore-turni:'+scope+':old']);console.log('OK service worker scope isolation');
reset();const workerSrc=run('sorgenteMotore()'),snapshot=run('JSON.stringify(state)');await new Promise((resolve,reject)=>{const w=new Worker(`const {parentPort}=require('node:worker_threads');global.self={postMessage:x=>parentPort.postMessage(x)};${workerSrc};parentPort.on('message',data=>self.onmessage({data}));`,{eval:true});w.on('error',reject);w.on('message',m=>{if(m.tipo==='errore'){w.terminate();reject(Error(m.messaggio));}if(m.tipo==='fine'){try{assert.equal(m.risultato.ok,true);w.terminate();resolve();}catch(e){reject(e);}}});w.postMessage(JSON.parse(snapshot));});console.log('OK separate worker uses same tested generator');
reset();run(`state.griglia=generaGriglia().griglia;ricalcolaStatsDaGriglia()`);const out=process.env.TURNI_TEST_OUTPUT;
if(out){fs.mkdirSync(out,{recursive:true});for(const [ext,fn] of [['docx','generaDOCX'],['xlsx','generaXLSX'],['pdf','generaPDF']])fs.writeFileSync(path.join(out,'baseline.'+ext),Buffer.from(await run(fn+'()').arrayBuffer()));
run(`state.persone=Array.from({length:40},(_,i)=>'PERSONA '+(i+1)+' COGNOME COMPOSTO MOLTO LUNGO');state.giorniSpeciali=[{giorno:15,etichetta:'Festa con squadra numerosa',cucina:state.persone.slice(0,20),servizio:state.persone.slice(20)}];state.regoleCustom=Array.from({length:40},(_,i)=>({tipo:'PREFERENZA_DATA',params:{persona:state.persone[i],giorno:1}}));`);
for(const stile of ['calendario','lista']){run(`state.stilePagina1='${stile}'`);fs.writeFileSync(path.join(out,'large-'+stile+'.pdf'),Buffer.from(await run('generaPDF()').arrayBuffer()));}}
console.log('All regression tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
